- LICENCE
> Add appropriate OSI licence

- static/i-dot-ai/base.css
Closes https://github.com/i-dot-ai/etf/issues/32
> Link progress steps together

- etf/templates/evaluation_list.html
- static/i-dot-ai/base.css
- Added style to override built-ins to match preferred style
- Added link to table row
- Run the design by Jude on slack :+1: 
Closes #60
> Added styling to search result table

- etf/evaluation/views.py
> Added login_required from django auth library to view.py

- etf/templates/allauth/account/base.html
- etf/templates/allauth/account/login.html
- etf/templates/allauth/account/logout.html
- etf/templates/allauth/account/signup.html
- etf/templates/base.html
- etf/templates/dates.html
- etf/templates/description.html
- etf/templates/end.html
- etf/templates/ethics.html
- etf/templates/evaluation_list.html
- etf/templates/index.html
- etf/templates/intro.html
- etf/templates/issue.html
- etf/templates/macros.html
- etf/templates/my-evaluations.html
- etf/templates/participant-recruitment.html
- etf/templates/search-form.html
- etf/templates/search-results.html
- etf/templates/title.html
- Added endfile lines where missing
- Fixed template indentation for one template
- Added whitespace into jinja2 template statements
Closes #79
> Jinja2 styling

- tests/__init__.py
> Add Django setup to tests

- etf/templates/description.html
- etf/templates/ethics.html
- etf/templates/issue.html
- etf/templates/macros.html
- etf/templates/participant-recruitment.html
- etf/templates/title.html
- Converted macros to use loop to allow tooltips to have paragraphed layout
- Added field descriptions to each field based on CO ETF specification
Closes #76
> Field descriptions

- .github/workflows/proxy.yml
Made a change to proxy.yml to clean up some code and trigger a proxy deployment
> Trigger proxy deployment

- etf/templates/allauth/account/login.html
- etf/templates/allauth/account/logout.html
- etf/templates/allauth/account/signup.html
- Replaced django supplied forms with custom forms
- Matched id's and names to existing fields
- Corrected sentence case throughout app
Closes #90
> Text fields changing in account forms

- static/i-dot-ai/base.css
Closes https://github.com/i-dot-ai/etf/issues/104
Co-Authored-By @mel-am
> Makes the .wrapper class have a consistent padding and border

- etf/evaluation/views.py
- etf/templates/base.html
- etf/templates/search-form.html
- etf/templates/search-results.html
- static/i-dot-ai/base.css
- static/i-dot-ai/layouts.css
- static/i-dot-ai/table.css
- static/i-dot-ai/text.css
** Possibly still move the form around, but first pass **
- Re-arranged search form fields
- Added ID to searchable properties
- Added search to top bar, along with a "Go" and "Advanced Search" button
- Added search on enter to top bar search field
- Added required styles for laying out the top bar
Closes #110
> Search form refinement

- etf/evaluation/views.py
- etf/templates/evaluation-list.html
- etf/templates/evaluation-summary.html
- etf/templates/macros.html
- etf/urls.py
- static/i-dot-ai/layouts.css
- Updated evaluation list to nav to evaluation summary
- Added evaluation summary page
- Added views and urls required
- Added nav to evaluation summary page to evaluation edit
- Added conditional check to allow/disallow user from getting to evaluation edit based on whether they're assigned
Closes #127
> Evaluation summary view

- .github/workflows/checks.yml
- .github/workflows/create-services.yml
- .github/workflows/deploy.yml
- .github/workflows/set-envs.yml
- cfscripts/etf-services.sh
- etf/settings.py
- manifests/staging/etf_manifest.yml
Add staging manifest and staging to action configs
> Update to deploy to staging

- envs/tests
- envs/web
- etf/evaluation/restrict_email_adapter.py
- etf/evaluation/views.py
- etf/settings.py
- etf/templates/allauth/account/signup.html
- etf/urls.py
- Added allowed domains to settings
- Added variable to web and tests env files to allow example domain
Closes #103
> Restrict to CO domains

- etf/settings.py
To allow user researcher to access -have created ticket #150 as a reminder to remove once user testing is done.
> add email domain for user testing

- README.md
- Just a simple one to improve readme
> Added more commands to the readme for easy access

- etf/evaluation/views.py
- etf/templates/page-not-found.html
- etf/urls.py
- Added 404 handler to urls.py
- Added related view to views.py
- View requires request and exception arguments per django docs
Closes #100
> Added 404 redirect

- etf/settings.py
- etf/templates/base.html
- requirements-dev.lock
- requirements-dev.txt
- tests/test_search.py
Added a failing test for the search page (which is blowing up).  Also made messages actually appear on the page (eg when you log in)
> Failing test for search

- etf/templates/submissions/description.html
- etf/templates/submissions/title.html
Update field names and descriptions on a couple of the pages.
> update field names and descriptions

- static/i-dot-ai/base.css
> Show form errors on page

- etf/templates/allauth/account/base.html
- etf/templates/base.html
> Amended header

- tests/test_registration.py
Add sample test for email validation
Closes #230
> Add initial registration test

- etf/templates/submissions/other-measure-page.html
> add fields for other measures

- etf/evaluation/submission_views.py
- etf/templates/macros.html
- etf/templates/submissions/processes-standard-page.html
> update process and standard page

- etf/evaluation/fakers.py
- Added new fields to evaluations created in fakers
- Added new generators for list items
Closes #148
> Added new properties to fakers.py

- etf/templates/macros.html
> Set textarea default height to 3 rows

- tests/test_registration.py
> Adding test for user registration.

- envs/web
- etf/jinja2.py
- etf/settings.py
> Add space_name

- web/src/style/components.css
- web/src/style/template.css
> bug fix for accordion spacing

- etf/templates/beta/beta-extra.html
- web/src/main.ts
- web/src/style/base.css
- web/src/style/buttons.css
> creation of buttons

- etf/evaluation/views.py
- etf/templates/search-form.html
> Added url to list of returned data to facilitate using JS to submit form

- etf/evaluation/email_handler.py
> handle none case if no previous login

- .github/workflows/deploy.yml
- .github/workflows/proxy.yml
downloads CLI from our own s3 bucket
> self hosted cf cli download

- etf/evaluation/overview_views.py
- etf/evaluation/views.py
- etf/templates/overview/evalaution-overview-measured.html
- etf/templates/overview/evaluation-overview-analysis.html
- etf/templates/overview/evaluation-overview-costs.html
- etf/templates/overview/evaluation-overview-design.html
- etf/templates/overview/evaluation-overview-findings.html
- etf/templates/overview/evaluation-overview.html
- etf/urls.py
- New overview_views.py
- New urls section
- New folder and pages in templates
> Added evaluation summary pages for each section

- etf/templates/overview/evaluation-overview.html
Added Jude because she found it on dev
> Bugfix for link not being found

- etf/templates/overview/evaluation-overview-analysis.html
- etf/templates/overview/evaluation-overview-costs.html
- etf/templates/overview/evaluation-overview-measured.html
> Added headers to multiple-object sections in side-nav

- etf/jinja2.py
- etf/templates/add-contributor.html
- etf/templates/contributor-rows.html
- etf/templates/contributors.html
- etf/templates/evaluation-list.html
- etf/templates/macros.html
- etf/templates/overview/evaluation-overview-analysis.html
- etf/templates/overview/evaluation-overview-costs.html
- etf/templates/overview/evaluation-overview-design.html
- etf/templates/overview/evaluation-overview-findings.html
- etf/templates/overview/evaluation-overview-measured.html
- etf/templates/overview/evaluation-overview.html
- etf/templates/remove-contributor.html
- etf/templates/search-form.html
- etf/templates/submissions/end.html
- etf/templates/submissions/evaluation-base.html
- etf/templates/submissions/overview.html
- Changed all uses of url to use new url reverse search
- Changed all N/A to Not answered
- Changed all field checks to more concise way of checking for empty values
> Summary refinement (url pipe and field checks)

- etf/evaluation/models.py
- tests/test_models.py
For child objects of an evaluation e.g. interventions
Closes #360
> Added extra model that saves parents on save

- .github/workflows/checks.yml
- Makefile
- docker-compose.yml
- docker/web/Dockerfile
> Test and Build css files

- README.md
- etf/templates/base.html
- etf/templates/beta/beta-pagedashboard.html
- web/src/style/base.css
- web/src/style/components/breadcrumb.css
- web/src/style/components/progress-list.css
- web/src/style/template/main-header.css
Closes #617
Closes #613
Closes #614
> Link updates

- etf/templates/base.html
- web/src/main.ts
> Bug fix: for web components not running

- etf/evaluation/pages.py
- etf/templates/submissions/document-page.html
- etf/templates/submissions/evaluation-costs.html
- etf/templates/submissions/process-analysis.html
- etf/templates/submissions/process-design.html
- etf/templates/submissions/process-findings.html
- etf/urls.py
- tests/test_enter_evaluation.py
- tests/test_pages.py
- Remove text relating to placeholders
- Remove pages that are only placeholders (subject to comment in #637 )
Closes #637
> Remove placeholders

- etf/templates/evaluation-list.html
- etf/templates/overview/evaluation-overview-analysis.html
- etf/templates/overview/evaluation-overview-costs.html
- etf/templates/overview/evaluation-overview-design.html
- etf/templates/overview/evaluation-overview-findings.html
- etf/templates/overview/evaluation-overview-measured.html
- etf/templates/overview/evaluation-overview.html
- etf/templates/submissions/evaluation-base.html
- web/src/style/base.css
- web/src/style/components/card.css
> spacing: Introduction of component header. Default spacing for h*

- etf/templates/macros.html
> Fixed allowing markdown in guidance text

- envs/tests
- etf/settings.py
> Added secure cookie setting

- etf/templates/beta/beta-extra.html
- etf/templates/overview/evaluation-overview-costs.html
- etf/templates/overview/evaluation-overview-measured.html
- etf/templates/overview/evaluation-overview.html
> Removed lorem ipsum from overview pages

- etf/templates/allauth/account/base.html
- etf/templates/base.html
> Amended phase to alpha

- etf/evaluation/submission_views.py
- Added object_name to each multiple object page
- Added object_name to data fed to templates
Fiex #694
> Added object_name to multiple object pages to correctly identify guidance text

- etf/evaluation/fields.py
- etf/evaluation/submission_views.py
- Added help and guidance text for create page to fields.py
- Updated the view for the create page to pass in object name so that the text can be found
> Help and guidance text on create page

- web/src/style/components/buttons.css
> Update button css

- etf/templates/allauth/account/verify_email_from_token.html
> Add header style

- etf/templates/allauth/account/password_reset_from_key_done.html
> Updated password changed header

- etf/templates/allauth/account/password_reset_from_key.html
> Updated set password header

- etf/templates/submissions/evaluation-base.html
> Removed section status

- etf/templates/submissions/evaluation-base.html
- removed contributors button
- Change back to evaluation to say: 'Manage evaluation
Closes #722
> Updated side panel

- etf/templates/index.html
The language was a bit garbled. Edited for clarity.
> Small content edit. Update index.html

- etf/templates/submissions/multiple-objects-page.html
- web/src/style/components/card.css
> Bug fix: Change priority of buttons

- envs/web
- etf/evaluation/authentication_views.py
- etf/evaluation/session_middleware.py
- etf/settings.py
- Added rolling timeout of 24 hours
- Added option to refresh the session on every request to facilitate rolling timeout
- Added check to sessions to time users out after 7 days if they're still logged in by using a custom option on the session
Closes #569
> Added session timeouts

- web/src/style/base.css
> Spacing fix

- etf/evaluation/pages.py
- tests/test_enter_evaluation.py
- tests/test_pages.py
- Removed documents page from evaluation creation list
- Removed documents page from progress list
Closes #529
> Remove documents pages

- etf/evaluation/restrict_email.py
- etf/templates/allauth/account/base.html
> Updated domain support message

- etf/templates/allauth/account/signup.html
> Updated register labels

- etf/evaluation/submission_views.py
- etf/templates/index.html
- web/src/style/pages.css
> New account homepage

- etf/evaluation/submission_views.py
> Removed user_id from user filter

- etf/templates/index.html
> Update dynamic value

- etf/templates/submissions/outcome-measures.html
> Minor content change

- etf/templates/beta/beta-extra.html
- etf/templates/macros.html
- web/src/components/dropdown.ts
- web/src/main.ts
- web/src/stories/Form/Select.stories.ts
- web/src/stories/utils.ts
- web/src/style/forms/index.css
- web/src/style/forms/select.css
> Select changed to web component

- etf/templates/macros.html
- web/src/components/multiselect.ts
- web/src/main.ts
- web/src/stories/Form/Multiselect.stories.ts
- web/src/stories/utils.ts
- web/src/style/components/chip.css
- web/src/style/forms/index.css
- web/src/style/forms/multiselect.css
- web/src/style/template/index.css
Closes #282
- Javascript enhanced multiselect. 
- toggle selection
- chip integration
- chip close event
- Storybook documentation
> Multiselect improvement

- etf/templates/submissions/intro.html
> Evaluation step 1 design alignment

- web/src/components/filters.ts
- web/src/stories/Card.stories.ts
- web/src/stories/Filter.stories.ts
- web/src/stories/types.ts
- web/src/stories/utils.ts
Further documentation on Cards, Accordion and Filters
> Documentation: Cards, Accordion

- etf/evaluation/submission_views.py
- etf/templates/submissions/evaluation-base.html
> Added evaluaiton title to each page in the submission process

- etf/allowed_domains.py
DAC are not able to sign up for accounts, I believe this should fix this
> 846 accessibility tester email domain not working

- etf/templates/submissions/issue-description.html
Re-wrote the overview text on the issue description page so that it is shorter and more concise.
> Update to overview text in issue-description.html

- etf/evaluation/schemas.py
- tests/test_schemas.py
- Added custom validator to choice fields that allow None as an option
Closes #806
> Added ability to choice fields for dropdowns to be optional

- etf/evaluation/pages.py
- etf/evaluation/submission_views.py
> change title to description and organisations

- etf/evaluation/fields.py
> Content change on Update fields.py

- etf/evaluation/fields.py
Removed / and changed to ,
Thanks Nina for spotting it needed to be changed in line 244 too.
> Content changes to Update fields.py

- etf/evaluation/fields.py
Changed the sub-title description for the field 'Fidelity'
> Content change to fields.py

- etf/templates/submissions/other-measures.html
Re-wrote the overview text to make it clearer and more concise, and 'match' the format of the overview text on the outcome measures page.
> Content change other-measures.html

- etf/templates/submissions/intervention-page.html
Renamed the field headings to be consistent
> Content changes to intervention-page.html

- etf/templates/submissions/economic-analysis.html
- etf/templates/submissions/other-analysis.html
- etf/templates/submissions/other-design.html
- etf/templates/submissions/process-evaluation-methods.html
> Placeholders removed

- web/src/components/multiselect.ts
> Bug fix: Value collection for multiselect

- web/src/components/utils.ts
- web/src/main.ts
- web/src/stories/Form/Input.stories.ts
> number field upgrade

- etf/evaluation/views.py
- etf/templates/allauth/account/login.html
- etf/templates/allauth/account/signup.html
- etf/templates/terms-and-conditions.html
- etf/urls.py
- tests/test_access_evaluations.py
> Terms and conditions

- etf/templates/overview/evaluation-overview-analysis.html
- etf/templates/overview/evaluation-overview-costs.html
- etf/templates/overview/evaluation-overview-design.html
- etf/templates/overview/evaluation-overview-findings.html
- etf/templates/overview/evaluation-overview-measured.html
- etf/templates/overview/evaluation-overview.html
> Removed contact buttons

- etf/evaluation/utils.py
- tests/test_access_evaluations.py
> Require login for overview views

- etf/evaluation/submission_views.py
> Fix default value for aspect thingies

- etf/evaluation/submission_views.py
- etf/templates/macros.html
- etf/templates/submissions/process-evaluation-method-page.html
- Converted generator for aspect names to list
- Added case to checklist_from_list macro for when the given list is empty
- Added warning message to the aspect name field when the list is empty
Fixes #844
> Incorrect display on process evaluation method page
